/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectopaint.presentacion;



import javax.swing.JButton;
import javax.swing.JPanel;



/**
 *
 * @author henry duarte
 */
public class Principal extends javax.swing.JFrame {
    
private ModeloPrincipal modeloPrincipal;

    private PrincipalController controlVistaPrincipal;
    /**
     * Creates new form Principal
     */
    public Principal(ModeloPrincipal _modeloPrincipal ) {
        this.modeloPrincipal = _modeloPrincipal;
        initComponents();
        capturaEventos();
        
        
    }
    
   
      private void capturaEventos() {
       
        this.jButtLinea.addActionListener(getController());
        this.jButtCircle.addActionListener(getController());
        this.jButtSquare.addActionListener(getController());
        this.jButtPencil.addActionListener(getController());
   
    }  
      
      
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
  
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelHeader = new javax.swing.JPanel();
        jButtLinea = new javax.swing.JButton();
        jButtSquare = new javax.swing.JButton();
        jButtCircle = new javax.swing.JButton();
        jButtPencil = new javax.swing.JButton();
        Lienzo = new java.awt.Canvas();
        drawPanelGenerico = new proyectopaint.presentacion.DrawPanelGenerico(this.modeloPrincipal);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 300));
        setSize(new java.awt.Dimension(600, 400));

        jPanelHeader.setBackground(new java.awt.Color(204, 204, 204));
        jPanelHeader.setLayout(new java.awt.GridLayout(1, 0));

        jButtLinea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectopaint/recursos/line.png"))); // NOI18N
        jButtLinea.setBorder(null);
        jPanelHeader.add(jButtLinea);

        jButtSquare.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectopaint/recursos/cuadrado.png"))); // NOI18N
        jButtSquare.setBorder(null);
        jButtSquare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtSquareActionPerformed(evt);
            }
        });
        jPanelHeader.add(jButtSquare);

        jButtCircle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectopaint/recursos/circle.png"))); // NOI18N
        jButtCircle.setBorder(null);
        jPanelHeader.add(jButtCircle);

        jButtPencil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectopaint/recursos/lapiz.png"))); // NOI18N
        jButtPencil.setBorder(null);
        jPanelHeader.add(jButtPencil);

        Lienzo.setMinimumSize(new java.awt.Dimension(300, 100));
        Lienzo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LienzoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LienzoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                LienzoMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout drawPanelGenericoLayout = new javax.swing.GroupLayout(drawPanelGenerico);
        drawPanelGenerico.setLayout(drawPanelGenericoLayout);
        drawPanelGenericoLayout.setHorizontalGroup(
            drawPanelGenericoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        drawPanelGenericoLayout.setVerticalGroup(
            drawPanelGenericoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelHeader, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Lienzo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(drawPanelGenerico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Lienzo, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(drawPanelGenerico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LienzoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LienzoMousePressed
        System.err.println("INICIANDO PULSACION DE MAUS");
        
      

    }//GEN-LAST:event_LienzoMousePressed

    private void LienzoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LienzoMouseReleased
       System.err.println("FIN  PULSACION DE MAUS");
       
    }//GEN-LAST:event_LienzoMouseReleased

    private void LienzoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LienzoMouseClicked

        

    }//GEN-LAST:event_LienzoMouseClicked

    private void jButtSquareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtSquareActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtSquareActionPerformed

   
  
  public PrincipalController getController() {
        if(controlVistaPrincipal == null){
            controlVistaPrincipal = new PrincipalController(this);
        }
        return controlVistaPrincipal;
    }
  

    public JButton getjButtLinea() {
        return jButtLinea;
    }

    public void setjButtLinea(JButton jButtLinea) {
        this.jButtLinea = jButtLinea;
    }

    public JButton getjButtCircle() {
        return jButtCircle;
    }

    public void setjButtCircle(JButton jButtCircle) {
        this.jButtCircle = jButtCircle;
    }

    public JButton getjButtPencil() {
        return jButtPencil;
    }

    public void setjButtPencil(JButton jButtPencil) {
        this.jButtPencil = jButtPencil;
    }

    public JButton getjButtSquare() {
        return jButtSquare;
    }

    public void setjButtSquare(JButton jButtSquare) {
        this.jButtSquare = jButtSquare;
    }

   

   
    

 

    
    
    public static DrawPanelGenerico getDrawPanelGenerico() {
        return drawPanelGenerico;
    }

    public static void setDrawPanelGenerico(DrawPanelGenerico drawPanelGenerico1) {
        Principal.drawPanelGenerico = drawPanelGenerico1;
    }

   

    public JPanel getjPanelHeader() {
        return jPanelHeader;
    }

    public void setjPanelHeader(JPanel jPanelHeader) {
        this.jPanelHeader = jPanelHeader;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Canvas Lienzo;
    public static proyectopaint.presentacion.DrawPanelGenerico drawPanelGenerico;
    private javax.swing.JButton jButtCircle;
    private javax.swing.JButton jButtLinea;
    private javax.swing.JButton jButtPencil;
    private javax.swing.JButton jButtSquare;
    private javax.swing.JPanel jPanelHeader;
    // End of variables declaration//GEN-END:variables

    
}
